server.port=8080
server.mode=release
gorm.log-level=info

# go-spring gorm starter
spring.gorm.main.url=root:123456@tcp(localhost:3306)/infra_market?charset=utf8mb4&parseTime=True&loc=Local

# go-spring redis starter
spring.go-redis.main.addr=localhost:6379
spring.go-redis.main.password=
spring.go-redis.main.driver=DefaultDriver
